

import React from 'react';
import * as ReactRouterDOM from 'react-router-dom';
import { useContent } from '../../hooks/useContent';
import toast from 'react-hot-toast';

const AdminGalleryListPage: React.FC = () => {
  const { galleryImages, deleteGalleryImage } = useContent();

  const handleDelete = (index: number) => {
    if (window.confirm('Are you sure you want to delete this gallery image?')) {
      deleteGalleryImage(index);
      toast.success('Image deleted from gallery!');
    }
  };

  return (
    <div>
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold text-white">Manage Gallery</h1>
        <ReactRouterDOM.Link to="/admin/gallery/new" className="bg-brand-primary px-4 py-2 rounded-lg font-semibold hover:opacity-90">
          Add New Image Manually
        </ReactRouterDOM.Link>
      </div>
      <div className="bg-brand-bg p-6 rounded-lg">
        <div className="space-y-4">
          {galleryImages.map((image, index) => (
            <div key={image.id} className="bg-brand-surface p-4 rounded-lg flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <img src={image.imageUrl} alt={image.title} className="w-24 h-16 rounded-md object-cover" />
                <div>
                  <h2 className="text-lg font-semibold text-white">{image.title}</h2>
                  <p className="text-sm text-brand-text-secondary truncate max-w-md">Prompt: {image.prompt}</p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <ReactRouterDOM.Link to={`/admin/gallery/${index}/edit`} className="text-brand-primary hover:text-white">
                  Edit
                </ReactRouterDOM.Link>
                <button onClick={() => handleDelete(index)} className="text-red-500 hover:text-red-400">
                  Delete
                </button>
              </div>
            </div>
          ))}
           {galleryImages.length === 0 && (
            <p className="text-brand-text-secondary text-center py-4">The gallery is currently empty. Images generated by users will appear here.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default AdminGalleryListPage;
